apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlplane
  namespace: edc-v
  labels:
    app: controlplane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controlplane
  template:
    metadata:
      name: controlplane
      labels:
        app: controlplane
    spec:
      containers:
        - name: controlplane
          image: controlplane:0.15.0-SNAPSHOT
          imagePullPolicy: Never
          envFrom:
            - configMapRef: { name: controlplane-config }
      restartPolicy: Always

---
---
apiVersion: v1
kind: Service
metadata:
  name: controlplane
  namespace: edc-v
spec:
  type: LoadBalancer
  selector:
    App: controlplane
  ports:
    - name: health
      port: 8080
      targetPort: 8080
    - name: management
      port: 8081
      targetPort: 8081
    - name: protocol
      port: 8082
      targetPort: 8082
    - name: debug
      port: 1044
      targetPort: 1044