apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: edc-v
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      name: nats
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:latest
          imagePullPolicy: IfNotPresent
          args:
            - "-js"
          ports:
            - containerPort: 4222
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: edc-v
spec:
  type: NodePort
  selector:
    app: nats
  ports:
    - name: nats
      port: 4222
      targetPort: 4222
