apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: edc-v
  labels:
    platform: edcv
    type: edcv-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
        platform: edcv
        type: edcv-infra
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:latest
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root"
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: "0.0.0.0:8200"
          args:
            - "server"
            - "-dev"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: edc-v

---
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-bootstrap
  namespace: edc-v
spec:
  template:
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: vault-cli
          image: hashicorp/vault:latest
          env:
            - name: VAULT_ADDR
              value: "http://vault.edc-v.svc.cluster.local:8200"
            - name: VAULT_TOKEN
              value: "root"
          command: [ "sh", "-c" ]
          args:
            - |
              # Enable JWT auth method
              vault auth enable userpass
              
              # Configure JWT auth (example: using Keycloak as JWT backend)
              vault write auth/jwt/config \
                jwks_url="http://keycloak.edc-v.svc.cluster.local:8080/realms/edcv/protocol/openid-connect/certs" \
                bound_issuer="http://keycloak.localhost/realms/edcv"
      restartPolicy: OnFailure

---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: edc-v
spec:
  selector:
    app: vault
  ports:
    - port: 8200
      targetPort: 8200

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: edc-v
spec:
  rules:
    - host: vault.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200