apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: edc-v
  labels:
    platform: edcv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
        platform: edcv
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:latest
        ports:
        - containerPort: 8200
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: "root"
        - name: VAULT_DEV_LISTEN_ADDRESS
          value: "0.0.0.0:8200"
        args:
        - "server"
        - "-dev"
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: edc-v
spec:
  selector:
    app: vault
  ports:
  - port: 8200
    targetPort: 8200

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: edc-v
spec:
  rules:
    - host: vault.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200